name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: harsh943/payment-wallet:latest  

    - name: Verify Pushed Image
      run: docker pull harsh943/payment-wallet:latest 

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull harsh943/payment-wallet:latest
          sudo docker stop payment-wallet || true
          sudo docker rm payment-wallet || true
          sudo docker run -d --name payment-wallet -p 3005:3000 harsh943/payment-wallet:latest


          # amazon alternative elastic beanstalk

          # deploy db on aws rds ->i can but wont 
          # if i have a db url then is houl replace the above lat run to below and add that to
          # github action secret
          # sudo docker run -e DATABASE_URL ${{SECRETS.DB_URL}} --restart-always -d --name payment-wallet -p 3005:3000 harsh943/payment-wallet:latest

          # further i can try uploading it on ecr instead of docker hub and then pull it to ECS;


          # Get a DB on neon.tech / RDS  / Aeiven and add a DB migration step to the DB
          # Pass in the DB credentials while starting the docker image
          # Start the docker image so that it restarts if it goes down (similar to pm2)
          # Infarstructure as code->same thing like this for lainching ec2 instance